#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=eval_Pruning
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=00:30:00
#SBATCH --output=./job_output/pruning/Eval_%A.out

module purge
module load 2023

# Activate conda environment
source activate thesis

# StarCoder2
for idx in {1..6}
do
  echo -e "\nEvaluating StarCoder2-3B, 128 tokens, $idx layers removed.\n"
  srun evalplus.evaluate --dataset humaneval --samples samples_decode/samples_3b_128_$idx-sanitized.jsonl
  echo -e "\nEvaluating StarCoder2-7B, 128 tokens, $idx layers removed.\n"
  srun evalplus.evaluate --dataset humaneval --samples samples_decode/samples_7b_128_$idx-sanitized.jsonl
done

# Phi-2
for idx in {1..6}
do
  echo -e "\nEvaluating Phi-2, 128 tokens, $idx layers removed.\n"
  srun evalplus.evaluate --dataset humaneval --samples samples_decode/samples_Phi2_128_$idx-sanitized.jsonl
done
